### ISSUE TITLE
Naive solver failure on mainnet

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#520]
I got this panic when running the naive solver on the mainnet contract.

`env ETHEREUM_NODE_URL=https://node.mainnet.gnosisdev.com NETWORK_ID=1 PRIVATE_KEY=0000000000000000000000000000000000000000000000000000000000000001 cargo run`
```
Feb 11 10:56:19.401 INFO [driver] Using contract at 0x6f40…841f
Feb 11 10:56:19.403 INFO [driver] Using account 0x7e5f…5bdf
Feb 11 10:56:19.403 INFO [driver::util] Using naive price finder
Feb 11 10:56:19.403 INFO [driver] Orderbook filter: OrderbookFilter { tokens: {}, users: {} }
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: core::option::Option<T>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
  15: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/collections/hash/map.rs:1035
  16: <driver::price_finding::naive_solver::NaiveSolver as driver::price_finding::price_finder_interface::PriceFinding>::find_prices
             at driver/src/price_finding/naive_solver.rs:169
  17: driver::driver::stablex_driver::StableXDriver::run
             at driver/src/driver/stablex_driver.rs:65
  18: driver::main
             at driver/src/main.rs:78
  19: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  23: std::panicking::try
             at src/libstd/panicking.rs:270
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  27: main
  28: __libc_start_main
  29: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by e00E** [comment]
This test reproduces the panic:
```rust
#[test]
fn temp_test_0() {
    let fee = Fee {
        token: 0,
        ratio: 0.5,
    };
    let orders = [
        Order {
            id: 0,
            account_id: H160::from_low_u64_be(0),
            sell_token: 0,
            buy_token: 1,
            sell_amount: 20 * BASE_UNIT,
            buy_amount: 10 * BASE_UNIT,
        },
        Order {
            id: 1,
            account_id: H160::from_low_u64_be(1),
            sell_token: 1,
            buy_token: 0,
            sell_amount: 10 * BASE_UNIT,
            buy_amount: 5 * BASE_UNIT,
        },
        Order {
            id: 2,
            account_id: H160::from_low_u64_be(2),
            sell_token: 0,
            buy_token: 2,
            sell_amount: BASE_UNIT,
            buy_amount: BASE_UNIT,
        },
    ];
    let state = AccountState::with_balance_for(&orders);

    let solver = NaiveSolver::new(Some(fee));
    let res = solver.find_prices(&orders, &state).unwrap();
}
```
Swap the last order's sell and buy token to crash at line 173 instead.

**Comment by e00E** [comment]
The problem is:

The naive solver only finds one match between two orders. For this match it sets the prices in a hashmap but not for the others. The second for loop which is responsible for handling the fee then iterates over all orders, not just the two matched orders which causes a panic when the `prices` hashmap is accessed for tokens that weren't part of the match.
